### ISSUE TITLE
Wrong distro info in Debian installation doc

### ISSUE THREAD

**Issue by Lukewh** [canonical-docs/snappy-docs#146]
## Summary

> On Debian snapd is available as part of the testing (currently ‘stretch’)

'stretch' is now stable, not testing.

## Process

[https://docs.snapcraft.io/core/install-debian](https://docs.snapcraft.io/core/install-debian)

*Copied from https://github.com/canonical-webteam-archive/snapcraft.io-static-pages/issues/397*

**Comment by matthewpaulthomas** [comment]
The page no longer mentions “testing”, so it looks like this has been fixed.
