### ISSUE TITLE
Typo in "Defining parts in snapcraft.yaml"

### ISSUE THREAD

**Issue by nottrobin** [canonical-docs/snappy-docs#168]
_From @dshcherb on January 12, 2017 20:51_

## Typo in "Defining parts in snapcraft.yaml"

"way" should be plural.
http://snapcraft.io/docs/build-snaps/parts
"Defining parts in snapcraft.yaml
plugin	(string)	Specifies the plugin that will manage this part. Snapcraft will pass the plugin all the other user-specified part options, those options defined with the other keys below. There are three **way** in which the plugin can be defined: a plugin name to use a built-in plug-in (for details, see the list of built-in plugins), a local path such as parts/plugins/x-plugin_name.py to use a local (custom defined) plugin and if plugin is not defined locally, the plugin defined for the part in the remote parts repository."

_Copied from original issue: canonical-webteam-archive/snapcraft.io-static-pages#259_

**Comment by matthewpaulthomas** [comment]
This was [fixed in March 2017](https://github.com/canonical-docs/snappy-docs/commit/f5c314c9f73b0d265a599a014c7896604bc6a6af#diff-5186424d06498a809c118191d1c0b495).
