### ISSUE TITLE
Best practice addition in tutorials: run apt update before apt install snapcraft

### ISSUE THREAD

**Issue by gsilvapt** [canonical-docs/snappy-docs#186]
As suggested in the [forums](https://forum.snapcraft.io/t/required-to-update-apt-before-installing-snapcraft), the LXD container guide should mention the user should run `apt update` before running `apt install snapcraft`, otherwise apt can not find snapcraft.

**Comment by matthewpaulthomas** [comment]
This was fixed by #187 in November. (And since then, the guide has changed to advise installing snapcraft as a snap instead.)

**Comment by gsilvapt** [comment]
Thank you!
