### ISSUE TITLE
Misspelled "Stanza" in snaps/philosophy.md

### ISSUE THREAD

**Issue by DubeyAdit** [canonical-docs/snappy-docs#210]
Incorrect spell for "Stanza" [here](https://github.com/canonical-docs/snappy-docs/search?utf8=%E2%9C%93&q=stenza&type=).

**Direction:**
* Change "Stenza" to "Stanza"

**Comment by matthewpaulthomas** [comment]
Thanks for the report. This is already reported as part of #156.
