### ISSUE TITLE
/build-snaps/register “Register your snap” returns 404 error

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-docs/snappy-docs#211]
1\. Go to [the main Docs page](https://docs.snapcraft.io/).
2\. Follow the “Publish your snap” > “Register your snap” link.

What happens: You end up at https://docs.snapcraft.io/build-snaps/register which returns a 404 error.

What should happen: You should not get a 404 error.

**Comment by DubeyAdit** [comment]
@matthewpaulthomas, This issue has been already mentioned #208. Also, it has been solved #209.
So I guess we should close this issue.
