### ISSUE TITLE
A small mistake in "Getting started" section

### ISSUE THREAD

**Issue by konrad11901** [canonical-docs/snappy-docs#221]
In "Getting started" section of C/C++ snap tutorial (/build-snaps/c), there is a small mistake.

It's written there:

> By way of an example, let’s take a look at how a C application can be snapped using snapcraft.

The example doesn't cover a C application - DOSBox is written in C++. The fragment: "a C application" should be changed to "a C++ application" or (more generally) to "a C/C++ application".

**Comment by popey** [comment]
Good catch! Thanks.

**Comment by matthewpaulthomas** [comment]
Fixed in #252.
