### ISSUE TITLE
"python setup.py egg_info" failed on snapcraft command with error code 1

### ISSUE THREAD

**Issue by rockinthespecs** [canonical-docs/snappy-docs#235]
When I typed this command I experienced a long error. (initial build of the snap)

**Comment by popey** [comment]
What application were you creating a snap of? Can you provide the snapcraft.yaml too?

**Comment by matthewpaulthomas** [comment]
The Snapcraft docs have been rewritten in the past few months, and as far as I can tell, they don’t mention `egg_info` at all ([1](https://forum.snapcraft.io/search?q=egg_info%20%23doc), [2](https://www.google.com/search?q=egg_info+site%3Adocs.snapcraft.io)). Please reopen this if you can identify a specific page that has this problem. Thanks.
