### ISSUE TITLE
Cannot open "youtube-dl_*.snap

### ISSUE THREAD

**Issue by Nissaar** [canonical-docs/snappy-docs#241]
After this code: 'sudo snap install youtube-dl_*.snap --devmode --dangerous'. It says 'error: cannot open: "youtube-dl_*.snap".

**Comment by popey** [comment]
Could you please paste the entire log of the build process?

**Comment by popey** [comment]
Looks like you're building in the wrong place. Should be building in your home directory, not in /snap using sudo. 
![4803807630327808_1513090589_1](https://user-images.githubusercontent.com/1841272/33901321-588f7688-df69-11e7-853b-44e98e6188b8.png)
