### ISSUE TITLE
Standardize Snapcraft install command in language tutorials

### ISSUE THREAD

**Issue by IvanFon** [canonical-docs/snappy-docs#245]
Many of the language tutorials have slightly different commands for installing Snapcraft.

To give some examples, the [Go](https://docs.snapcraft.io/build-snaps/go#building-the-snap), [Node](https://docs.snapcraft.io/build-snaps/node#building-the-snap) and [Java](https://docs.snapcraft.io/build-snaps/java#building-the-snap) pages install from the beta channel:
```bash
sudo snap install --beta --classic snapcraft
```

While the [Ruby](https://docs.snapcraft.io/build-snaps/ruby#building-the-snap), [Rust](https://docs.snapcraft.io/build-snaps/rust#building-the-snap) and [Electron](https://docs.snapcraft.io/build-snaps/electron#building-the-snap) pages install from the candidate channel:
```bash
sudo snap install --candidate --classic snapcraft
```
These aren't all of them, but they show the inconsistency.

Is there a reason that these shouldn't be left to the default (stable) channel, and if so, is there a reason that they differ based on language?

**Comment by popey** [comment]
Well spotted!
Now that snapcraft is in the stable channel, all the tutorials should simply say `sudo snap install snapcraft --classic`

**Comment by m4sk1n** [comment]
Aren't some plugins available only in beta version of snapcraft?
