### ISSUE TITLE
Command "python setup.py egg_info" failed

### ISSUE THREAD

**Issue by Nissaar** [canonical-docs/snappy-docs#247]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip.WxIpiu-build/

**Comment by popey** [comment]
Looks like we need to fix the python-six issue again..

![4803807630327808_1513107049_1](https://user-images.githubusercontent.com/1841272/33930305-5c69875a-dfe4-11e7-9b16-5c75934a6c48.png)
