### ISSUE TITLE
Traceback Errors When Building Python Snap in Python Snap Creation Tutorial 

### ISSUE THREAD

**Issue by DigiBrkr** [canonical-docs/snappy-docs#256]
I am working on a  QA task for the Google Code-in: the [Python Snap Creation Tutorial](https://docs.snapcraft.io/build-snaps/python). I believe I have found an issue in the OfflineIMAP section of this tutorial. 

Everything works great up to the point where I execute the `snapcraft` command. At that point, it has several tracebacks on the processing of the source code.  I believe these tracebacks are caused by  missing Python packages, here are the lines that lead me to that conclusion: 

```
Processing /home/DigiBrkr/offlineimap/parts/offlineimap/src
  Link is a directory, ignoring download_dir
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-8oJrGB-build/setup.py", line 26, in <module>
        import offlineimap
      File "offlineimap/__init__.py", line 20, in <module>
        from offlineimap.init import OfflineImap
      File "offlineimap/init.py", line 34, in <module>
        from offlineimap import threadutil, accounts, folder, mbnames
      File "offlineimap/accounts.py", line 23, in <module>
        import six
    ImportError: No module named six
```
I'm new to snapcraft and have only been coding in Python for a few months, but I believe this could be fixed by installing the following libraries:

* `threadutil`
* `accounts`
* `folder`
* `mbnames` 
* `six` 

I believe that is how this problem could be fixed. 

I will attach the the full log below.  

Thanks for reviewing my issue! 

[snapcraft.log](https://github.com/canonical-docs/snappy-docs/files/1559802/snapcraft.log)

**Comment by evandandrea** [comment]
Tracking in #263
