### ISSUE TITLE
Suggestion on snapcraft builds with C tutorial.

### ISSUE THREAD

**Issue by LaughingLove** [canonical-docs/snappy-docs#258]
Hello, I have a few suggestions for the C snap tutorial.

In the section "Confinement" they should add a reference to the different types of confinement, for users that want more information. [Here](https://docs.snapcraft.io/reference/confinement) is a link to it.

In the section "Parts" you should suggest users use the command:
`snapcraft help autotools`
for more information on the specific plugin that the tutorial is using to compile the source.

In the section "Share with your friends", in the string "...using the email address attached to your Snap Store account:", you should add "using your [Ubuntu One account](https://login.ubuntu.com)", so that people will know that they sign one using their Ubuntu One credentials.

**Comment by matthewpaulthomas** [comment]
In the linked PR I’ve applied the first two suggestions.

I haven’t mentioned “using your Ubuntu One account”, because I think that’s interesting only when you’re first creating the Snap Store account.
