### ISSUE TITLE
Python snap-creation of offlineimap leads to module six error!

### ISSUE THREAD

**Issue by LaughingLove** [canonical-docs/snappy-docs#260]
Hello, I have seen the same exact error posted as an issue [here](https://github.com/canonical-docs/snappy-docs/issues/256), [here](https://github.com/canonical-docs/snappy-docs/issues/223), and [here](https://github.com/canonical-docs/snappy-docs/issues/247), but to no avail. I am deciding to post the same error to get more attention for this problem.

When following the snap-creation tutorial on offlineimap [here](https://docs.snapcraft.io/build-snaps/python), it tells you to clone the repo and then run `snapcraft`, I did so and I got the error attached in this issue. Briefly, it says:
`ImportError: No module named six`

So I tried to do `pip install six` then run it again, but it did not work either.

Since I've seen this same exact error posted several times here. I consider this a problem with offlineimap.

Screenshot:

![offlineimap error](https://user-images.githubusercontent.com/34354312/34067324-4943ba3e-e1f0-11e7-8dd0-e51aa46532c4.png)

Here is the full log:
[offlineimap.txt](https://github.com/canonical-docs/snappy-docs/files/1564502/offlineimap.txt)

**Comment by evandandrea** [comment]
Tracking in #263
