### ISSUE TITLE
Snap registration link to dashboard is broken

### ISSUE THREAD

**Issue by cprov** [canonical-docs/snappy-docs#262]
Since the recent changes on dashboard.s.io URL schema, the link to register snaps in the webui is broken (2x) in https://docs.snapcraft.io/build-snaps/register-snap

The correct URL is `https://dashboard.snapcraft.io/register-snap/`

**Comment by evandandrea** [comment]
Shouldn't the dashboard redirect from the old link to the new one?

**Comment by matthewpaulthomas** [comment]
Looks like @caldav fixed one of the broken links on January 18th. In #375 I fix the other one.
