### ISSUE TITLE
Error in installing snap (Python)

### ISSUE THREAD

**Issue by omairqazi** [canonical-docs/snappy-docs#269]
```
sudo snap install offlineimap_*.snap --devmode --dangerous
```
The above mentioned code produces an error cannot open xxxxxxxx.snap .
```
sudo snap install offlineimap_*.snap --devmode --dangerous
error: cannot open: "offlineimap_*.snap"

```
Viewer/User gets confused and will not be able to follow this step:

> You can then try it out:
> 
> `offlineimap`

**Comment by evandandrea** [comment]
Hi @omairqazi,

Can you please attach the output of `sudo strace -e file -f -u $USER snap install --dangerous offlineimap_*.snap`?

**Comment by omairqazi** [comment]
got this issued fixed by myself
