### ISSUE TITLE
Build using cleanbuild (was Getting an error, when runnign youtube-dl on Ubuntu 17.10)

### ISSUE THREAD

**Issue by nbelenkov** [canonical-docs/snappy-docs#270]
When trying to run youtube-dl it produces this error on Ubuntu 17.10:
```

bate@MacBook:~/Desktop/projects/googlecodein/youtube-dl$  sudo snap install youtube-dl_*.snap --devmode --dangerous 
youtube-dl 2017.06.18 installed
bate@MacBook:~/Desktop/projects/googlecodein/youtube-dl$ youtube-dl 
/snap/youtube-dl/x2/usr/bin/python3: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /snap/youtube-dl/x2/usr/bin/python3)
```

**Comment by evandandrea** [comment]
I suspect this is because the snap is being built using 17.10. I've confirmed it works in 16.04.

**Comment by evandandrea** [comment]
@sergiusens is this a case we can detect inside snapcraft and surface an appropriate error?

We can obviously update the docs to guide people through `snapcraft cleanbuild`, but I don't think we can expect everyone to read them.

**Comment by nbelenkov** [comment]
@evandandrea Just ran `snapcraft cleanbuild` and got no errors. You should maybe mention that if you got errors by just using `snapcraft`, you should try `snapcraft cleanbuild`.
