### ISSUE TITLE
Store API reference is hidden

### ISSUE THREAD

**Issue by matthewpaulthomas** [canonical-docs/snappy-docs#344]
The Snap Store has [a thorough API reference](https://dashboard.snapcraft.io/docs/).

This API is useful for vendors who have an internal CI system, especially if it does not run on Linux.

Unfrotunately, these documents aren’t even linked to from anywhere obvious — let alone integrated with the rest of the snap+Snapcraft documentation.

What should happen: “Store API” should be a category on [docs.snapcraft.io](https://docs.snapcraft.io/).

[Originally mentioned by Martin Wimpress @flexiondotorg.]

**Comment by evandandrea** [comment]
At the same level as Reference or within Reference?

**Comment by matthewpaulthomas** [comment]
I’m just one person, and good card-sorting requires more than that — but I do not think “Reference” is a useful category. (It results in, for example, two pages labelled “Interfaces” in separate sections.)

I would choose to put all “Store”-related information together: “[Register](https://docs.snapcraft.io/build-snaps/register-snap)”, “[Upload](https://docs.snapcraft.io/build-snaps/upload)”, “[Release](https://docs.snapcraft.io/build-snaps/release)”, and “API”. Short of that, I think a top-level section would be better than going inside “Reference”.

**Comment by matthewpaulthomas** [comment]
Looks like one step in this process would be [configuring Sphinx to output Markdown](http://www.sphinx-doc.org/en/master/usage/markdown.html) rather than HTML.

**Comment by nottrobin** [comment]
https://docs.snapcraft.io is now generated from https://forum.snapcraft.io/c/doc.

If this API documentation should be human-written documentation, then this discussion and solution should be moved to the Discourse forum.

If we're talking about hosting auto-generated API documentation on https://docs.snapcraft.io, could you please file an issue to that effect on https://github.com/canonical-websites/docs.snapcraft.io ?
