### ISSUE TITLE
skype snap does not find microphone / webcam (manjaro/i3)

### ISSUE THREAD

**Issue by konstantinstadler** [canonical-docs/snappy-docs#351]
Trying snap for skype on linux, I get
"No device found" for both, microphone and speakers. 
The website opening clicking "Lear more" does not provide any help.

However, it works fine on skype online in Chromium

System info:
System:    Host: IEPT1150 Kernel: 4.14.9-2-MANJARO x86_64 bits: 64 Desktop: i3 4.14.1 Distro: Manjaro Linux
Machine:   Device: desktop System: Dell product: Precision T3610 v: 01 serial: N/A
           Mobo: Dell model: 09M8Y8 v: A01 serial: N/A BIOS: Dell v: A06 date: 02/28/2014
CPU:       6 core Intel Xeon E5-1650 v2 (-MT-MCP-) cache: 12288 KB
           clock speeds: max: 3900 MHz 1: 3491 MHz 2: 3491 MHz 3: 3491 MHz 4: 3491 MHz 5: 3491 MHz 6: 3491 MHz
           7: 3491 MHz 8: 3491 MHz 9: 3491 MHz 10: 3491 MHz 11: 3491 MHz 12: 3491 MHz
Graphics:  Card: NVIDIA GK106GL [Quadro K4000]
           Display Server: x11 (X.Org 1.19.5 ) drivers: nouveau (unloaded: modesetting)
           Resolution: 2560x1440@59.95hz, 2560x1440@59.95hz
           OpenGL: renderer: NVE6 version: 4.3 Mesa 17.3.1
Audio:     Card-1 NVIDIA GK106 HDMI Audio Controller driver: snd_hda_intel Sound: ALSA v: k4.14.9-2-MANJARO
           Card-2 Intel C600/X79 series High Definition Audio Controller driver: snd_hda_intel
           Card-3 Creative Labs Sound Core3D [Sound Blaster Recon3D / Z-Series] driver: snd_hda_intel
           Card-4 Logitech driver: USB Audio
           Card-5 Logitech Headset H390 driver: USB Audio
Network:   Card: Intel 82579LM Gigabit Network Connection (Lewisville) driver: e1000e
           IF: enp0s25 state: up speed: 1000 Mbps duplex: full mac: f8:b1:56:cb:0e:a0
Drives:    HDD Total Size: 3024.6GB (14.1% used)
           ID-1: /dev/sdb model: ST2000DM001 size: 2000.4GB
           ID-2: /dev/sda model: Samsung_SSD_850 size: 1024.2GB
Partition: ID-1: / size: 870G used: 177G (22%) fs: ext4 dev: /dev/sda1
           ID-2: swap-1 size: 74.26GB used: 0.00GB (0%) fs: swap dev: /dev/sda2
Sensors:   System Temperatures: cpu: 43.0C mobo: N/A gpu: 44.0
           Fan Speeds (in rpm): cpu: N/A
Info:      Processes: 262 Uptime: 46 days Memory: 10247.0/64375.6MB Client: Shell (zsh) inxi: 2.3.53
k

**Comment by matthewpaulthomas** [comment]
This does not seem to be anything to do with snappy-docs. For help with Skype, see https://support.skype.com/en/skype/linux/.
