### ISSUE TITLE
Install snap example uses wrong snap options

### ISSUE THREAD

**Issue by 8none1** [canonical-docs/snappy-docs#363]
https://docs.snapcraft.io/build-snaps/your-first-snap

Using this example, the command to install the snap is given as:

$ sudo snap install hello_2.10_*.snap --dangerous
hello 2.10 installed

However, it seems the correct syntax is now --devmode

**Comment by caldav** [comment]
`--devmode` implies `--dangerous`, so when walking through building a generic (strict) snap, I think it's more useful to expose `--dangerous` (which applies to classic, strict and devmode snaps) than just `--devmode`. What do you think?

**Comment by 8none1** [comment]
Yeah, I think this might well have been user error actually.
