### ISSUE TITLE
Update project site URL

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [canonical-docs/snappy-docs#447]
![default](https://user-images.githubusercontent.com/13408130/46952234-da517280-d0bc-11e8-8c8b-c58273cb5478.png)

The docs.snapcraft.io no longer hosts the old documentation site, we should probably drop the URL field or update it if we want to host it again with a different host domain.

**Comment by degville** [comment]
thanks for flagging this - fixing it now.
